version: '3.8'

services:
  date-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: date-service
    ports:
      - "8081:8081"
    networks:
      - date-service-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  date-service-network:
    name: library-network
    driver: bridge
    external: true